import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Search,Flame,ShieldCheck,ExternalLink,RefreshCw,Sparkles,AlertTriangle}from'lucide-react';import'./styles.css';
const countries=[['US','United States'],['GB','United Kingdom'],['ES','Spain'],['CA','Canada'],['AU','Australia'],['DE','Germany'],['FR','France'],['IT','Italy'],['IN','India'],['BR','Brazil'],['MX','Mexico'],['JP','Japan']];
const Badge=({children,kind='neutral'})=><span className={'badge '+kind}>{children}</span>;
const Meter=({score})=>{const label=score>=85?'Excellent':score>=70?'Strong':score>=55?'Promising':score>=40?'Weak':'Low';return <div className="meter"><div className="score">{score}</div><div><strong>{label}</strong><span>/100 forecast</span></div></div>};
function App(){const[seed,setSeed]=useState(''),[geo,setGeo]=useState('US'),[count,setCount]=useState(10),[format,setFormat]=useState('pdf'),[loading,setLoading]=useState(false),[data,setData]=useState(null),[error,setError]=useState('');const canRun=seed.trim().length>=2&&!loading;const country=useMemo(()=>countries.find(x=>x[0]===geo)?.[1]||geo,[geo]);
async function analyze(e){e?.preventDefault();if(!canRun)return;setLoading(true);setError('');setData(null);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({seed,geo,count:Number(count),format})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Analysis failed');setData(j)}catch(e){setError(e.message||'Something went wrong')}finally{setLoading(false)}}
return <div className="page"><header><div className="brand"><div className="logo"><Flame size={19}/></div><div><b>TrendForge</b><span>Evidence-backed idea radar</span></div></div><div className="truth"><ShieldCheck size={16}/> No fake volume</div></header><main><section className="hero"><Badge kind="green">LIVE SIGNALS + TRANSPARENT FORECASTS</Badge><h1>Find product ideas<br/><em>before they get crowded.</em></h1><p>Ranks ideas from live search suggestions and current trend signals. Every idea gets its own 1–100 rating with the evidence shown.</p></section>
<form className="panel" onSubmit={analyze}><div className="wide field"><label>Niche / seed topic</label><div className="inputIcon"><Search size={17}/><input value={seed} onChange={e=>setSeed(e.target.value)} placeholder="e.g. ADHD routines, meal prep, AI freelancing"/></div></div><div className="field"><label>Country</label><select value={geo} onChange={e=>setGeo(e.target.value)}>{countries.map(([c,n])=><option key={c} value={c}>{n}</option>)}</select></div><div className="field"><label>Number of ideas</label><select value={count} onChange={e=>setCount(Number(e.target.value))}>{[5,10,15,20,25,50].map(n=><option key={n} value={n}>{n}</option>)}</select></div><div className="field"><label>Product type</label><select value={format} onChange={e=>setFormat(e.target.value)}><option value="pdf">PDF / printable</option><option value="digital">Digital product</option><option value="website">Website / web app</option></select></div><button disabled={!canRun} className="run">{loading?<><RefreshCw className="spin" size={17}/> Reading live signals…</>:<><Sparkles size={17}/> Find opportunities</>}</button></form>
<div className="method"><div><b>Observed</b><span>Live source data</span></div><div><b>Estimated</b><span>Derived proxy</span></div><div><b>Forecast</b><span>1–100 opportunity prediction</span></div></div>
{error&&<div className="error"><AlertTriangle size={17}/>{error}</div>}
{data&&<section className="results"><div className="resultsHead"><div><Badge kind="green">{Math.min(data.ideas.length,data.query?.count||data.ideas.length)} ranked ideas</Badge><h2>{seed} — {country}</h2></div><div className="fresh">Updated {new Date(data.generatedAt).toLocaleString()}</div></div><div className="sourceRow">{data.sources.map((s,i)=><a key={i} href={s.url} target="_blank" rel="noreferrer">{s.name}<ExternalLink size={12}/></a>)}</div><p className="disclaimer"><b>Accuracy:</b> autocomplete appearances/ranks and current-trend matches are observed. Demand values are proxies derived from those observations. The 1–100 score is a forecast, not a promise of virality or sales. This app never invents monthly search volume.</p><div className="cards">{data.ideas.slice(0,data.query?.count||data.ideas.length).map((x,i)=><article className="card" key={x.id}><div className="rank">#{i+1}</div><div className="cardTop"><div><div className="badges"><Badge kind={x.evidence.googleAutocomplete?'green':'neutral'}>Google {x.evidence.googleAutocomplete?'observed':'not seen'}</Badge><Badge kind={x.evidence.youtubeAutocomplete?'purple':'neutral'}>YouTube {x.evidence.youtubeAutocomplete?'observed':'not seen'}</Badge>{x.evidence.currentTrend&&<Badge kind="orange">Current trend</Badge>}<Badge>{x.confidence} confidence</Badge></div><h3>{x.title}</h3><p>{x.angle}</p></div><Meter score={x.score}/></div><div className="metrics"><div><span>Demand evidence</span><b>{x.metrics.demand}/100</b><small>Estimated from live suggestion rank + repetition</small></div><div><span>Trend momentum</span><b>{x.metrics.trend}/100</b><small>Observed/estimated from live trend overlap</small></div><div><span>Problem intent</span><b>{x.metrics.intent}/100</b><small>Forecast from query wording</small></div><div><span>Product fit</span><b>{x.metrics.productFit}/100</b><small>Forecast for selected format</small></div></div><div className="evidence"><b>Why it scored</b><span>{x.evidence.summary}</span></div><div className="keywords"><b>Observed queries</b>{x.evidence.queries.slice(0,5).map(q=><code key={q}>{q}</code>)}</div></article>)}</div></section>}
</main><footer>TrendForge · Evidence first. Forecast second.</footer></div>}
createRoot(document.getElementById('root')).render(<App/>);