const GEO_LANG={US:'en',GB:'en',ES:'es',CA:'en',AU:'en',DE:'de',FR:'fr',IT:'it',IN:'en',BR:'pt',MX:'es',JP:'ja'};
const MODIFIERS=['how to','checklist','planner','template','guide','routine','tracker','for beginners','problems','ideas','printable','workbook','schedule','plan','tips','mistakes'];
const FORMAT_WORDS={pdf:['checklist','planner','template','guide','routine','tracker','printable','workbook','schedule','plan','journal','worksheet','cheat sheet'],digital:['template','tracker','planner','calculator','generator','dashboard','toolkit','notion','spreadsheet','course','guide'],website:['calculator','generator','finder','tracker','checker','planner','dashboard','converter','search','tool']};
const INTENT_WORDS=['how to','fix','stop','avoid','without','help','problem','mistake','checklist','plan','routine','schedule','guide','template','tracker','best way','for beginners','step by step'];
const clamp=n=>Math.max(0,Math.min(100,Math.round(n)));
const clean=s=>String(s||'').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').trim();
const tok=s=>clean(s).toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>2);
function overlap(a,b){const A=new Set(tok(a)),B=new Set(tok(b));if(!A.size||!B.size)return 0;let x=0;for(const t of A)if(B.has(t))x++;return x/Math.min(A.size,B.size)}
async function getJson(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 TrendForge/1.0','accept':'application/json,text/plain,*/*'},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error('source '+r.status);return r.json()}
async function getText(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 TrendForge/1.0','accept':'application/rss+xml,text/xml,*/*'},signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error('source '+r.status);return r.text()}
async function suggest(q,geo,hl,yt=false){const u=new URL('https://suggestqueries.google.com/complete/search');u.searchParams.set('client','firefox');u.searchParams.set('q',q);u.searchParams.set('gl',geo);u.searchParams.set('hl',hl);if(yt)u.searchParams.set('ds','yt');const j=await getJson(u);return Array.isArray(j?.[1])?j[1].map(clean).filter(Boolean):[]}
function trends(xml){const out=[];for(const m of xml.matchAll(/<item>([\s\S]*?)<\/item>/g)){const b=m[1],title=clean((b.match(/<title>([\s\S]*?)<\/title>/)||[])[1]),traffic=clean((b.match(/<ht:approx_traffic>([\s\S]*?)<\/ht:approx_traffic>/)||[])[1]);if(title)out.push({title,traffic})}return out}
function makeTitle(q,format){let x=clean(q).replace(/^how to\s+/i,'').replace(/\s+/g,' ');x=x.replace(/\b\w/g,c=>c.toUpperCase());if(format==='website')return x+' Tool';if(format==='digital')return x+' Toolkit';if(/checklist|planner|template|guide|routine|tracker|printable|workbook|schedule|plan|journal|worksheet/i.test(x))return x;return x+': Practical Guide'}
function angle(q,format){if(format==='website')return 'A focused web tool built around the observed search phrase “'+q+'”, with one clear job and fast results.';if(format==='digital')return 'A reusable digital toolkit that directly answers the observed query “'+q+'” with templates, steps and tracking.';if(/checklist/i.test(q))return 'A concise printable checklist that helps someone complete this task without missing steps.';if(/planner|schedule|routine|plan/i.test(q))return 'A printable action plan designed for repeated daily or weekly use.';if(/template|tracker/i.test(q))return 'A ready-to-use printable/template product built directly around the observed need.';return 'A practical PDF that directly solves the need expressed by this observed search query.'}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'POST only'});const body=req.body||{},seed=clean(body.seed).slice(0,80),geo=String(body.geo||'US').toUpperCase(),format=['pdf','digital','website'].includes(body.format)?body.format:'pdf',limit=Math.max(3,Math.min(50,Number(body.count)||10)),hl=GEO_LANG[geo]||'en';if(seed.length<2)return res.status(400).json({error:'Enter a niche or seed topic.'});
const promptSet=[seed,...MODIFIERS.map(m=>seed+' '+m)].slice(0,13);
let g=[],y=[],trendRows=[],gOk=true,yOk=true,tOk=true;
const tasks=await Promise.allSettled([Promise.all(promptSet.map(q=>suggest(q,geo,hl,false))),Promise.all(promptSet.slice(0,8).map(q=>suggest(q,geo,hl,true))),getText('https://trends.google.com/trending/rss?geo='+encodeURIComponent(geo))]);
if(tasks[0].status==='fulfilled')g=tasks[0].value;else gOk=false;if(tasks[1].status==='fulfilled')y=tasks[1].value;else yOk=false;if(tasks[2].status==='fulfilled')trendRows=trends(tasks[2].value);else tOk=false;
if(!gOk&&!yOk)return res.status(502).json({error:'Live suggestion sources are temporarily unavailable. Try again shortly.'});
const map=new Map();function ingest(groups,source){groups.forEach((arr,pi)=>arr.forEach((q,ri)=>{if(overlap(q,seed)<.45)return;const k=q.toLowerCase();const v=map.get(k)||{q,gRanks:[],yRanks:[],prompts:new Set()};if(source==='g')v.gRanks.push(ri+1);else v.yRanks.push(ri+1);v.prompts.add(pi);map.set(k,v)}))}
ingest(g,'g');ingest(y,'y');let rows=[...map.values()];if(!rows.length)rows=[{q:seed,gRanks:gOk?[10]:[],yRanks:yOk?[10]:[],prompts:new Set([0])}];
const seedTokens=new Set(tok(seed));rows=rows.filter(r=>{const q=new Set(tok(r.q));let common=0;for(const t of seedTokens)if(q.has(t))common++;return common>=Math.max(1,Math.ceil(seedTokens.size*.5))});
const scored=rows.map((r,idx)=>{const gBest=r.gRanks.length?Math.min(...r.gRanks):99,yBest=r.yRanks.length?Math.min(...r.yRanks):99,appear=r.gRanks.length+r.yRanks.length,cross=r.gRanks.length&&r.yRanks.length;let demand=18+Math.min(42,appear*7)+(gBest<99?Math.max(0,20-gBest*2):0)+(yBest<99?Math.max(0,12-yBest):0)+(cross?10:0);demand=clamp(demand);
const matchedTrends=trendRows.filter(t=>overlap(t.title,r.q)>=.5||overlap(t.title,seed)>=.7);let trend=matchedTrends.length?Math.min(100,65+matchedTrends.length*10):25;if(!tOk)trend=20;
const low=r.q.toLowerCase();const intentHits=INTENT_WORDS.filter(w=>low.includes(w)).length;const intent=clamp(40+intentHits*18+(low.length>seed.length+5?8:0));const fitHits=(FORMAT_WORDS[format]||[]).filter(w=>low.includes(w)).length;const productFit=clamp(48+fitHits*22+(format==='pdf'&&/how to|guide|checklist|planner|template|routine|tracker|workbook|schedule|plan/.test(low)?12:0));const score=clamp(demand*.43+trend*.17+intent*.22+productFit*.18);const sources=(r.gRanks.length?1:0)+(r.yRanks.length?1:0)+(matchedTrends.length?1:0);const confidence=sources>=3?'high':sources===2?'medium':'low';
const bits=[];if(r.gRanks.length)bits.push('Google autocomplete observed'+(gBest<99?' as high as position '+gBest:''));if(r.yRanks.length)bits.push('YouTube autocomplete observed'+(yBest<99?' as high as position '+yBest:''));if(matchedTrends.length)bits.push('overlaps '+matchedTrends.length+' current Google Trends item'+(matchedTrends.length>1?'s':''));if(appear>1)bits.push('repeated across '+appear+' live suggestion lists');if(!bits.length)bits.push('limited live evidence');
return{id:'i'+idx,title:makeTitle(r.q,format),angle:angle(r.q,format),score,confidence,metrics:{demand,trend,intent,productFit},evidence:{googleAutocomplete:!!r.gRanks.length,youtubeAutocomplete:!!r.yRanks.length,currentTrend:!!matchedTrends.length,summary:bits.join('; ')+'.',queries:[r.q,...new Set([...g.flat(),...y.flat()].filter(x=>x.toLowerCase()!==r.q.toLowerCase()&&overlap(x,r.q)>.72))].slice(0,6)}}});
const uniq=[],seen=[];for(const x of scored.sort((a,b)=>b.score-a.score)){if(seen.some(s=>overlap(s,x.title)>.9))continue;seen.push(x.title);uniq.push(x);if(uniq.length>=limit)break}
return res.status(200).json({generatedAt:new Date().toISOString(),query:{seed,geo,format,count:limit},sources:[...(gOk?[{name:'Google Search autocomplete (live)',url:'https://www.google.com/search?q='+encodeURIComponent(seed)}]:[]),...(yOk?[{name:'YouTube autocomplete (live)',url:'https://www.youtube.com/results?search_query='+encodeURIComponent(seed)}]:[]),...(tOk?[{name:'Google Trends Trending Now (live)',url:'https://trends.google.com/trending?geo='+encodeURIComponent(geo)}]:[])],method:{score:'43% demand evidence + 17% current-trend overlap + 22% problem intent + 18% product fit',warning:'Score is a forecast. Autocomplete/trend appearances are observed; demand/intent/product-fit are derived proxies.'},ideas:uniq});}